### ISSUE TITLE
Creates new sheet called 'Refresh', cells keep moving

### ISSUE THREAD

**Issue by doncullen** [rghuckins/robinhood-google-sheets#1]
Just wanted a cell that'd display the full balance in the account, including cash.  Saw no way to pull up that information directly (tried =ROBINHOOD_GET_PORTFOLIOS(equity_portfolios), it displayed all content), so I created a new sheet called RobinHood, put the reference to the full content displayed by ROBINHOOD_GET_PORTFOLIOS, then in my original sheet, I referenced the same cell that contained the value of 'equity_portfolios'.  Displayed the desired info, great!

Then I hit refresh in browser to confirm the value updated to the latest balance value.  That's when it broke.  I saw a new sheet tab called "Refresh" with nothing in it, and when I looked at RobinHood sheet, instead of the function being in A1, it was now at A17.   I'm not sure why it's creating new tab or moving the cells around.

**Comment by rghuckins** [comment]
@doncullen did you end up resolving this issue? If so, and if the resolution involved a code change, would you be interested in making a pull request? One thing to note: `ROBINHOOD_GET_PORTFOLIOS()` will always return a table containing all columns so passing `"equity_portfolios"` to the function will not return a single value (i.e. the full balance in the account). The code in its current form shouldn't move any cells -- although it does create a "Refresh" sheet if it doesn't already exist.

**Comment by doncullen** [comment]
No, I wasn't able to resolve it.  Due to the inability to get a single specific value and due to it creating a "refresh" sheet (unwanted behavior), I removed it and am updating the balance manually until a workaround is available.  I have a financial sheet that reports how I am doing financially in all areas (retirement, savings, checking, budget management, etc); I've been trying to automate alot of what I do, hence why I was interested in this script.
