### ISSUE TITLE
Robinhood API request failed. 400.{"inactive instruments":["S"]}. line 90

### ISSUE THREAD

**Issue by ParitoshKelkar** [rghuckins/robinhood-google-sheets#12]
Hi, 

I'm getting this error on call to the RH_GET_POSITIONS() function.
The RH_GET_ORDERS() and RH_GET_WATCHLIST() are working. 

The GET_POSITIONS() was working until around a couple of days ago ...

**Comment by Cjkelble** [comment]
I am getting the same. I looks to be the case where the API is trying to get data for a company that has been delisted. I am getting the issue for UTX.

**Comment by samdavidson** [comment]
@ParitoshKelkar @Cjkelble 

https://github.com/rghuckins/robinhood-google-sheets/issues/3#issuecomment-470720584

**Comment by Cjkelble** [comment]
This didn't work. It now says there is an internal error in the code.
