### ISSUE TITLE
Skip stocks that no longer exist and/or are not tradable on Robinhood

### ISSUE THREAD

**Issue by rghuckins** [rghuckins/robinhood-google-sheets#3]
Reporting an issue brought up by @xtego

https://github.com/rghuckins/robinhood-google-sheets/commit/a42df8e9498c5bb2aa4908dd065e7a077794e885#commitcomment-29282798

> I just stumbled across this code today and it's awesome. Thanks so much for your work that you put into this. However, I think i have uncovered a bug given certain scenarios using get positions and get orders. I am getting the following error : "Robinhood API request failed. 404: (line 107)"
Using google's debug tools, it looks like it's failing on a ticker that no longer exists.
For example, I used to own a position in RPRX which no longer exists in robinhood. This is causing robinhood_get_positions() and robinhood_get_orders() to error. Other functions like robinhood_get_portfolios() are working fine for me.
Unfortunately, that's about the best I can help. I'm not a good enough coder to fix it, but I was wondering if you or someone else had an easy fix to the code to skip over tickers that don't exist.

**Comment by kkgundelli** [comment]
Did you find the fix for the error? I came across the same error with a different ticker. Please share what you found.

**Comment by andrewmahoneyf** [comment]
This can be fixed by simply filtering out any old positions by checking the quantities. I was only concerned about positions but you could do something similar for orders as well.
```
function getRobinhoodData_(endpoint, hyperlinkedFields) {
  var data = [];
  var url = robinhoodApiBaseUrl + robinhoodApiUriMap[endpoint];
  var results = apiClient.pagedGet(url);

 // add lines below
  if (endpoint == "positions") {
    results = results.filter(function (row) {
      return row['quantity'] > 0;
    });
  }
 ...
```

**Comment by samdavidson** [comment]
thanks a lot @andrewmahoneyf
