### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by CannedSplam** [rghuckins/robinhood-google-sheets#4]
I am getting this error when I try to run the script or use any function in my sheet.

SyntaxError: Unexpected token: < (line 41, file "Code")

Why is this and how do I fix it?

**Comment by CannedSplam** [comment]
@rghuckins Let me know on this

**Comment by zameschua** [comment]
I ran into this problem and I found out that Robinhood recently deprecated their `/api-token-auth` endpoint, and migrated it over to `/oauth2/token`

I managed to make my script work by roughly following this link: https://github.com/aurbano/robinhood-node/pull/78/files

I'll create a pull request with the changes to upgrade to Oauth2
